### ISSUE TITLE
bug: Integrators should always try to infer pixel size from array, or error, not use a default value

### ISSUE THREAD

**Issue by pbeaucage** [usnistgov/PyHyperScattering#20]
There is currently a default pixel1/pixel2 value in the Nika parameter loader of 0.027 mm, from the ALS instrument.  This makes no sense for any other instrument.  Integrators should not use a default value here - either source it from instantiation, source it from the array to be read, or raise an exception.

Thanks @dsunday for finding this one.

**Comment by EliotGann** [comment]
one way that I have fudged this in the past, is to have a dirty look up table based on the number of pixels x.y in an image, which is a pretty good indication of what the ccd is, and so what the pixel size is.  In particular for the SST1 instrument, the default binning is 4x4, resulting in 1024 pixels that are 60um square, but if you bin a 2x2, there are 2048 pixels that are 30um square etc etc, so if someone accidentally changes the binning, things still work... the problem is the beam center is completely wrong but hey, you can't solve everything with a dirty look up table.  I believe the PIMTE (ALS 11.0.1.2), and all of the pilati have unique numbers of pixels, so it might work.
