### ISSUE TITLE
Multiple tests failing on KeyError: Energy

### ISSUE THREAD

**Issue by pdudenas** [usnistgov/PyHyperScattering#41]
There are a number of tests [failing or raising errors](https://github.com/usnistgov/PyHyperScattering/runs/8275420630?check_suite_focus=true#step:9:754) on a KeyError: Energy exception, that seems to be related to the multiindex. See the WPintegrator traceback for an [example](https://github.com/usnistgov/PyHyperScattering/runs/8275420630?check_suite_focus=true#step:9:715). 

Confusingly, the WPIntegrator works great with no errors or exceptions on some recent CyRSoXS data I have.

**Comment by pbeaucage** [comment]
Interesting...is this specific to WPIntegrator and the cyrsoxs tool chain, or failing in other places too?

**Comment by pdudenas** [comment]
Doesn't fail but an error is raised 7 times in test_RSoXS. (Lines 754-760)[https://github.com/usnistgov/PyHyperScattering/runs/8275420630?check_suite_focus=true#step:9:754]

**Comment by pbeaucage** [comment]
OK, I understand this now.

It's raised in test_RSoXS just because those tests run against cyrsoxs data for convenience.

My earlier code for #39 greedily eats multi indexes; this is a problem because cyrsoxsloader makes a multiindex of 1 variable for energy.  (Why?  Ask me from months ago....). The two appear to not be playing nicely.

My suggested fix is to just make energy a regular index and coordinate in the return, not a multiindex.  No idea if that will work.

**Comment by pbeaucage** [comment]
cyrsoxsLoader.py:123-125 is where I'd look to implement a simpler version.

**Comment by pdudenas** [comment]
Replaced the multi-index with an 'energy' index. test_cyrsoxsLoader, test_WPintegrator, and test_RSoXS all pass now.

Side note: test_SST1Loader and test_11012Loader pass on python 3.6 & 3.7, but fail on python 3.8
